### ISSUE TITLE
[Error] data 추출 오류 

### ISSUE THREAD

**Issue by parkseonga** [Doyun-lab/capstone_project#2]
아래와 같은 코드 작성 시 첫번째 코드 실행이 잘되는데 두 번째는 데이터 값이 첫번째 값만 나오고 나머지는 모두 NA로 반환됩니다.

왜인지 알 수 있을까요?

```
get(file_list)$IBP1[1:nrow(get(file_list))*0.25]

```

```
get(file_list)$IBP1[nrow(get(file_list))*0.85:nrow(get(file_list))]

```

@pmsk98 @Doyun-lab

**Comment by Doyun-lab** [comment]
왜 인지는 저도 모르겠으나

  start = round(nrow(get(file_list))*0.85)
  end = nrow(get(file_list))

  v_end.AMOC = cpt.var(get(file_list)$IBP1[start:end],method = "AMOC")

로 해결할 수 있겠네요
