### ISSUE TITLE
[Preprocessing] 전처리 순서에 관하여 

### ISSUE THREAD

**Issue by Doyun-lab** [Doyun-lab/capstone_project#4]
3sigma로 이상치를 제거했더니 대체로 잘 잘리는 모습을 볼 수 있었습니다.

그래서,
1. 3 sigma - 보간법 - diff로 튀는 값 제거
2. 3 sigma - cpt.var - 보간법 - diff로 튀는 값 제거

두 가지 방법 중 잘 나오는 방법을 택하여 하는 것이 좋을 것 같습니다.

**Comment by parkseonga** [comment]
좋아요!
